Document: build2-toolchain
Title: Debian build2-toolchain Manual
Author: <insert document author here>
Abstract: This manual describes what build2-toolchain is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/build2-toolchain/build2-toolchain.sgml.gz

Format: postscript
Files: /usr/share/doc/build2-toolchain/build2-toolchain.ps.gz

Format: text
Files: /usr/share/doc/build2-toolchain/build2-toolchain.text.gz

Format: HTML
Index: /usr/share/doc/build2-toolchain/html/index.html
Files: /usr/share/doc/build2-toolchain/html/*.html
